services:
  stats-server:
    build: server
    image: explore-server
    container_name: explore-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=explore
      - POSTGRES_USER=explore
      - POSTGRES_DB=explore
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://explore:explore@db:5432/explore -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE TABLE IF NOT EXISTS stats (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          uri VARCHAR(255) NOT NULL,
          app VARCHAR(255) NOT NULL,
          ip VARCHAR(100) NOT NULL,
          time timestamp NOT NULL,
          hits BIGINT NOT NULL,
          unique_hits BIGINT NOT NULL
        );
        EOSQL